return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "prettier",
        "black",
        "isort",
        "autoflake",
        "flake8",
        "yamllint",
        "jsonlint",
        "stylua",
        "rustfmt",
        "go-debug-adapter",
        "gofumpt",
        "goimports",
        "goimports-reviser",
        "golangci-lint",
        "golangci-lint-langserver",
        "golines",
        "gomodifytags",
        "gopls",
        "gotests",
        "gotestsum",
        "staticcheck",
        -- "terraform-fmt",
        "shfmt",
        "beautysh",
        "shellcheck",
        "bash-debug-adapter",
        "bash-language-server",
        -- "opacheck",
        "pyright",
        "json-lsp",
        "yamllint",
        "yamlfmt",
        "terraform-ls",
        "tflint",
        "marksman",
        "rust-analyzer",
        "ansible-language-server",
      },
    },
  },
}
